Repository mdazfar2/HelpOps-Hub, pull requests merged in 2024-05, with the labels that each got.

#28 added workflow as per issue #7
  .github/workflows/autocomment-issue.yml
Labels: documentation, Workflow

#29 added workflow as per issue #8
  .github/workflows/autocomment-pr-raise.yml
Labels: Workflow, gssoc, level2

#31 added workflow as per issue #10
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level2

#30 added workflow as per issue #9
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, level2

#33 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc, level2

#32 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: gssoc, level2

#37 added issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/project.yml
Labels: gssoc, level2

#41 Create Learn.md
  Learn.md
Labels: documentation, gssoc, level2

#43 Add Security and Compliance section to learn.md
  Learn.md
Labels: documentation, good first issue, gssoc, level1
