Repository mdazfar2/HelpOps-Hub, pull requests merged in 2024-07, with the labels that each got.

#764 Added github Provider with backend integration and Added proper popup
  website3.0/components/AuthButton.js
  website3.0/components/Login-Signup.js
  website3.0/pages/HomePage.js
  website3.0/src/app/api/auth/[...nextauth]/route.js
  website3.0/src/app/api/createaccount/route.js
  website3.0/src/app/api/signup/route.js
Labels: gssoc, level3, web enhance, work done, great work, backend, Authentication

#767 Fixed Multiple account creation
  website3.0/components/AuthButton.js
  website3.0/pages/HomePage.js
  website3.0/src/app/api/createaccount/route.js
Labels: gssoc

#766 Feat: .hamburger close icon add
  website3.0/components/Header.js
  website3.0/package-lock.json
  website3.0/stylesheets/header.css
Labels: pending, need change

#774 Added Forgot Password Functionality
  package.json
  website3.0/components/Login-Signup.js
  website3.0/components/Reset.js
  website3.0/package.json
  website3.0/pages/HomePage.js
  website3.0/src/app/api/changepass/route.js
  website3.0/src/app/api/forgotpassword/route.js
  website3.0/stylesheets/reset.css
Labels: bug, invalid, WIP, pending, isn't me

#783 fixed api fetching issue
  website3.0/pages/ResourcesPage.js
Labels: gssoc, level3, great work

#793 Added integration with backend for Uploading image to profile and removed login/signup button after loging
  website3.0/components/AuthButton.js
  website3.0/components/Login-Signup.js
  website3.0/pages/HomePage.js
  website3.0/pages/Profile.js
  website3.0/src/app/api/createaccount/route.js
  website3.0/stylesheets/profile.css
  website3.0/utils/models/user.js
Labels: gssoc, level3, web enhance, work done, great work, backend, Authentication

#799 Added email icon in the newsletter input
  website3.0/pages/HomePage.js
  website3.0/stylesheets/homepage.css
Labels: gssoc, level1

#822 Integrated Blog's Page with Database-Added Logic for Top Posts,Recent Posts,Editor's Choice,Newsletter
  website3.0/pages/BlogPage.js
  website3.0/src/app/api/blog/route.js
  website3.0/stylesheets/blogspage.css
  website3.0/utils/models/blog.js
Labels: gssoc, level3, web enhance, work done, great work, backend, databse, Authentication

#851 Feat : responsive added in contact us page
  website3.0/pages/ContactPage.js
Labels: gssoc, level2

#853 Enhanced the Teams Page UI and added tailwind css
  website3.0/pages/TeamsPage.js
  website3.0/stylesheets/teams.css
  website3.0/tailwind.config.js
Labels: gssoc, level3, web enhance, work done, great work, code convert

#856 Feat:Want to Create UI Of Profile page #823
  .gitignore
  package-lock.json
  package.json
  website3.0/pages/ProfilePage.js
  website3.0/src/app/profile/page.js
  website3.0/stylesheets/profilepage.css
Labels: WIP, need change

#866 Modification in login Signup page ui ux
  website3.0/components/LoginSignup/Login.js
  website3.0/components/LoginSignup/Signup.js
  website3.0/stylesheets/login-signup.css
  website3.0/stylesheets/reset.css
Labels: gssoc, level2, great work

#893 Added Dark mode for About , Contact , profile , edit profile , Navbar and footer
  website3.0/components/AuthButton.js
  website3.0/components/Footer.js
  website3.0/components/Header.js
  website3.0/components/Logout.jsx
  website3.0/components/ProfilepageDetails.jsx
  website3.0/pages/AboutPage.js
  website3.0/pages/ContactPage.js
  website3.0/src/app/about/page.js
  website3.0/src/app/contact/page.js
  website3.0/src/app/profile/page.js
  website3.0/stylesheets/contact.css
  website3.0/stylesheets/header.css
  website3.0/stylesheets/profilepage.css
Labels: invalid, WIP, let you know, pending, isn't me

#907 Added error message when resource not found
  website3.0/pages/ResourcesPage.js
Labels: gssoc, level2, work done

#903 Feat:Convert Profile Page UI from CSS to Tailwind CSS #876
  website3.0/components/EditProfileModal.js
  website3.0/components/ProfilepageDetails.jsx
  website3.0/src/app/profile/page.js
  website3.0/stylesheets/profilepage.css
Labels: gssoc, level2, great work, code convert

#925 Add metatags for seo and fixed popup message spelling
  website3.0/components/Header.js
  website3.0/components/LoginSignup/Login.js
  website3.0/pages/HomePage.js
  website3.0/src/app/layout.js
Labels: gssoc, level2, work done, we need it

#929 Fixed uploading an image , user get logged out , Showing data of wrong user , email envelope link is not working etc
  website3.0/components/AuthButton.js
  website3.0/components/EditProfileModal.js
  website3.0/components/LoginSignup/Login.js
  website3.0/components/Logout.jsx
  website3.0/components/ProfilepageDetails.jsx
  website3.0/context/store.jsx
  website3.0/src/app/api/createaccount/route.js
Labels: gssoc, level2, web enhance, work done, great work, Authentication

#941 Fixed user accounts modals for different screen sizes
  website3.0/components/AuthButton.js
  website3.0/components/LoginSignup/Login.js
  website3.0/components/LoginSignup/Signup.js
  website3.0/components/Reset.js
  website3.0/pages/OTP.js
  website3.0/pages/Profile.js
  website3.0/src/app/layout.js
  website3.0/stylesheets/otp.css
  website3.0/stylesheets/reset.css
  website3.0/tailwind.config.js
Labels: gssoc, level2, web enhance, work done, great work, responsive

#950 Feat: Converted Whole Blogpage to TailwindCSS
  website3.0/pages/BlogPage.js
  website3.0/stylesheets/blogspage.css
Labels: gssoc, level2, great work, code convert

#1012 Fixed Navbar In blogs page
  website3.0/components/Header.js
  website3.0/components/Popup.js
  website3.0/pages/BlogPage.js
  website3.0/stylesheets/Popup.css
Labels: gssoc, level2, great work

#1015 Backend Integration for Creating post by all users , added ctrl+v feture to paste image , fixed popup , added validation to create post only if user login
  website3.0/components/AuthButton.js
  website3.0/components/Header.js
  website3.0/components/LoginSignup/Login.js
  website3.0/context/store.jsx
  website3.0/pages/BlogPage.js
  website3.0/pages/ContactPage.js
  website3.0/pages/Createblog.jsx
  website3.0/src/app/api/login/route.js
  website3.0/src/app/contact/page.js
  website3.0/stylesheets/Popup.css
  website3.0/stylesheets/blog.css
Labels: gssoc, level3, web enhance, work done, we need it, backend, databse

#1008 Feat: Want to make skeleteon For Dark mode #994
  website3.0/components/CardSkeleton.js
  website3.0/components/Loader.js
  website3.0/tailwind.config.js
Labels: gssoc, level2, great work

#1024 Fixed inputs
  website3.0/pages/Createblog.jsx
Labels: gssoc

#1030 Added the text editor for all input fields for text formatting and fixed bugs like height is not increasign automatically on text , text pasting is not working
  website3.0/components/Header.js
  website3.0/components/blogpage/BlogPost.js
  website3.0/components/blogpage/CreateBlog.js
  website3.0/package-lock.json
  website3.0/package.json
  website3.0/pages/BlogPage.js
  website3.0/pages/Createblog.jsx
  website3.0/src/app/createblog/page.js
  website3.0/stylesheets/editor.css
Labels: gssoc, level3, work done, great work, backend, databse

#1069 enhanced about page
  website3.0/package-lock.json
  website3.0/package.json
  website3.0/pages/AboutPage.js
Labels: WIP, pending, need change

#1098 Added smooth hover scale
  website3.0/pages/HomePage.js
Labels: WIP, pending

#1234 Added Ellipsis icon under the blog post
  website3.0/components/blogpage/BlogPost.js
Labels: gssoc, level1, great work

#1236 Backend Integrated for giving power to admin for adding the blog
  website3.0/components/admin/dashboard/AllBlogs.jsx
  website3.0/pages/AdminPanel.js
  website3.0/src/app/api/createaccount/route.js
Labels: gssoc, level2, great work, backend

#1239 Created Complete Backend API with database to storing the question data and created the complete model for that and fixed the bug with signin
  website3.0/components/forumpage/CreateForum.js
  website3.0/src/app/api/createaccount/route.js
  website3.0/src/app/api/createquestion/route.js
  website3.0/utils/models/newaccounts.js
  website3.0/utils/models/question.js
Labels: gssoc, level3, work done, great work, backend, databse

#1248 Integrated Complete Backend Integration For Response with complete frontend
  website3.0/components/forumpage/ForumPost.js
  website3.0/pages/ForumPage.js
  website3.0/src/app/api/questioncomment/route.js
  website3.0/utils/models/question.js
Labels: gssoc, level3, work done, great work, backend, databse

#1250 Backend Integrated for Close and Open the Issue and backend Integrated for user visits for each issue
  website3.0/components/forumpage/ForumPost.js
  website3.0/pages/ForumPage.js
  website3.0/src/app/api/closequestion/route.js
  website3.0/src/app/api/questionviews/route.js
  website3.0/src/app/devopsforum/page.js
  website3.0/utils/models/question.js
Labels: gssoc, level3, web enhance, work done, great work, backend

#1257 Completed Posting a Question with database Connectivity and Created Modal for solutions
  website3.0/components/forumpage/ForumPost.js
  website3.0/src/app/api/addsolution/route.js
  website3.0/src/app/devopsforum/page.js
  website3.0/utils/models/question.js
Labels: gssoc, level3, great work, backend, databse

#1258 Added Feature for Recent Topic and Top Topics in the Forums Page
  website3.0/components/forumpage/ForumPost.js
  website3.0/pages/ForumPage.js
Labels: gssoc, level1

#1260 Added The searching functionality for the Forums page
  website3.0/components/forumpage/ForumPost.js
Labels: gssoc, level2, great work
