Repository mdazfar2/HelpOps-Hub, pull requests merged in 2024-08, with the labels that each got.

#1269 Added validation for ask the question without login , fixed text overflowing from the question
  website3.0/components/forumpage/ForumPost.js
  website3.0/pages/ForumPage.js
  website3.0/src/app/devopsforum/page.js
Labels: gssoc, level2, great work

#1275 Created Backend for adding related users to the question and created a model for that
  website3.0/components/forumpage/ForumPost.js
  website3.0/pages/ForumPage.js
  website3.0/src/app/api/addsolution/route.js
  website3.0/src/app/api/createquestion/route.js
  website3.0/utils/models/question.js
  website3.0/utils/models/user.js
Labels: gssoc, level3, work done, great work, backend

#1282 Created the functionality for Most Helpful Component
  website3.0/components/profile/GrowYourReachTab.jsx
  website3.0/pages/ForumPage.js
  website3.0/src/app/api/getuserbyid/route.js
Labels: gssoc, level3, great work

#1302 Added THe feature to show the number of solutions provided and changed the icon before the Title
  website3.0/components/forumpage/ForumPost.js
Labels: gssoc, level1

#1307 Fix Cursor style on forums page reply btn
  website3.0/components/forumpage/ForumPost.js
Labels: gssoc, level1

#1304 Fixed the wrong Banner showing while signin with email and password
  website3.0/src/app/api/createaccount/route.js
Labels: gssoc, level2, great work

#1312 Replaced Many the img tag with Image tag of the next.js to improve the performance
  website3.0/components/Header.js
  website3.0/components/LoginSignup/Login.js
  website3.0/components/admin/dashboard/AllBlogs.jsx
  website3.0/pages/AdminPanel.js
  website3.0/pages/HomePage.js
  website3.0/pages/ResourcesPage.js
  website3.0/pages/TeamsPage.js
  website3.0/src/app/[...not_found]/page.js
Labels: gssoc, level2, great work

#1320 Added Devops Forums Question and Answer components from scratch to the profile
  website3.0/components/forumpage/ForumPost.js
  website3.0/components/profile/Answers.jsx
  website3.0/components/profile/Questions.jsx
  website3.0/pages/ForumPage.js
  website3.0/src/app/profile/page.js
Labels: gssoc, level3, work done, great work

#1333 Optmized the Api's Performance
  website3.0/src/app/api/averagetime/route.js
  website3.0/src/app/api/blockblog/route.js
  website3.0/src/app/api/changepass/route.js
  website3.0/src/app/api/checkusername/route.js
  website3.0/src/app/api/closequestion/route.js
  website3.0/src/app/api/deleteaccount/route.js
Labels: gssoc, level2, great work

#1331 Added Try catch BLock so that error will not displayed on deployed website
  website3.0/components/admin/dashboard/AllBlogs.jsx
  website3.0/components/admin/dashboard/Overview.js
  website3.0/components/blogpage/BlogPost.js
  website3.0/components/blogpage/CreateBlog.js
  website3.0/components/blogpage/Editblog.jsx
  website3.0/components/forumpage/ForumPost.js
  website3.0/components/profile/Answers.jsx
  website3.0/components/profile/EditProfileModal.jsx
  website3.0/components/profile/Questions.jsx
  website3.0/components/profile/SettingsTab.jsx
  website3.0/pages/BlogPage.js
Labels: gssoc, level2, great work

#1336 Added a ctrl + Enter behaviour to move on next page
  website3.0/components/blogpage/CreateBlog.js
  website3.0/components/forumpage/CreateForum.js
Labels: gssoc, level2, work done, great work
